# true 是启用
# false 是禁用
# 分组
pr:
  &pr {
    type: select,
    proxies:
      [
        🚀 节点选择,
        🇭🇰 香港节点,
        🇨🇳 台湾节点,
        🇯🇵 日本节点,
        🇸🇬 新加坡节点,
        🇺🇲 美国节点,
        其它地区,
        全部节点,
        🔃 自动选择,
        DIRECT,
      ],
  }
# 延迟检测 URL
p:
  &p {
    type: http,
    interval: 3600,
    health-check:
      {
        enable: true,
        url: http://cp.cloudflare.com/,
        interval: 300,
      },
  }

# 订阅名，记得修改成自己的
# 添删订阅在这里和下方订阅链接依葫芦画瓢就行
use: &use
  type: select
  use:
    - 订阅一
    - 本地配置

# 订阅链接
# 对于订阅来说，path 为选填项，但建议启用
# 本地配置可以只填 path
proxy-providers:
  订阅一:
    <<: *p
    url: 自己填



  本地配置:
    <<: *p
    url: 自己填

# 规则订阅
#rule-providers:
  # anti-AD 广告拦截规则
  # https://github.com/privacy-protection-tools/anti-AD
  # 如果误杀率高请自行更换
  anti-AD:
    type: http
    behavior: domain
    format: yaml
    # path可为空(仅限clash.meta 1.15.0以上版本)
    path: ./rule_provider/anti-AD.yaml
    url: "https://raw.githubusercontent.com/privacy-protection-tools/anti-AD/master/anti-ad-clash.yaml?"
    interval: 600
  # anti-AD 白名单规则
  anti-AD-white:
    type: http
    behavior: domain
    format: yaml
    # path可为空(仅限clash.meta 1.15.0以上版本)
    path: ./rule_provider/anti-AD-white.yaml
    url: "https://raw.githubusercontent.com/privacy-protection-tools/dead-horse/master/anti-ad-white-for-clash.yaml?"
    interval: 600

mode: rule
# ipv6 支持
ipv6: true
log-level: info
# 允许局域网连接
allow-lan: true
# socks5/http 端口
mixed-port: 7890
socks-port: 7891
# Meta 内核特性 https://wiki.metacubex.one/config/general
# 统一延迟
# 更换延迟计算方式,去除握手等额外延迟
unified-delay: true
# TCP 并发
# 同时对所有ip进行连接，返回延迟最低的地址
tcp-concurrent: true
# 外部控制端口
external-controller: :9090

geodata-mode: true

# Geo 数据库下载地址
# 使用 FastGit 代理 (https://fgit.cf)
# 源地址 https://github.com/MetaCubeX/meta-rules-dat
# 可以更换镜像站但不要更换其他数据库，可能导致无法启动
geox-url:
  geoip: "https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geoip-lite.dat"
  geosite: "https://hub.gitmirror.com/https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geosite.dat"
  mmdb: "https://hub.gitmirror.com/https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/country.mmdb"

# 进程匹配模式
# 路由器上请设置为 off
# always 开启，强制匹配所有进程
# strict 默认，由 Clash 判断是否开启
# off 不匹配进程，推荐在路由器上使用此模式
find-process-mode: strict

# 缓解移动设备耗电问题
# https://github.com/vernesong/OpenClash/issues/2614
keep-alive-interval: 30

# 全局客户端指纹
global-client-fingerprint: random # 随机指纹

# 缓存
profile:
  store-selected: true


# 域名嗅探
sniffer:
  enable: true
  sniff:
    TLS:
      ports: [443, 8443]
    HTTP:
      ports: [80, 8080-8880]
      override-destination: true

# tun 模式
tun:
  enable: false  # enable 'true'
  stack: system  # or 'gvisor'
  dns-hijack:
    - "any:53"
    - "tcp://any:53"
  auto-route: true
  auto-detect-interface: true

dns:
  enable: true
  ipv6: false
  listen: :23453
  enhanced-mode: redir-host
  prefer-h3: true
  nameserver-policy:
    "geosite:cn":
      - 218.192.255.252
      - 182.254.116.116
  nameserver:
    - https://doh2.fly.dev/dns-query
    - https://namlaf919j.cloudflare-gateway.com/dns-query
    - https://2owhqznrdt.cloudflare-gateway.com/dns-query

# 多入站端口设置
# listeners:
#   - name: hk
#     type: mixed
#     port: 12991
#     proxy: 香港

#   - name: tw
#     type: mixed
#     port: 12992
#     proxy: 台湾

#   - name: sg
#     type: mixed
#     port: 12993
#     proxy: 新加坡

proxies:
  # - name: "WARP"
  #   type: wireguard
  #   server: engage.cloudflareclient.com
  #   port: 2408
  #   ip: "172.16.0.2/32"
  #   ipv6: "2606::1/128"        # 自行替换
  #   private-key: "private-key" # 自行替换
  #   public-key: "public-key"   # 自行替换
  #   udp: true
  #   reserved: "abba"           # 自行替换
  #   mtu: 1280
  #   dialer-proxy: "WARP前置"
  #   remote-dns-resolve: true
  #   dns:
  #     - https://dns.cloudflare.com/dns-query

proxy-groups:
  # 使用 WARP 的用户需要手动在下方的 proxies 字段内添加 WARP
  # 例如 [WARP, 全部节点, 🔃 自动选择, 🇭🇰 香港节点, 🇨🇳 台湾节点, 🇯🇵 日本节点, 🇸🇬 新加坡节点, 🇺🇲 美国节点, 其它地区, DIRECT],
  - {
      name: 🚀 节点选择,
      type: select,
      proxies:
        [全部节点, 🔃 自动选择, 🇭🇰 香港节点, 🇨🇳 台湾节点, 🇯🇵 日本节点, 🇸🇬 新加坡节点, 🇺🇲 美国节点, 其它地区, DIRECT],
    }
  # 这里的 dns 指海外解析 dns 走的节点，一般跟随🚀 节点选择即可
  - { name: dns, <<: *pr }
  # WARP 配置链式出站
  # - { name: WARP前置, <<: *pr, exclude-type: "wireguard" }

#  - { name: 广告拦截, type: select, proxies: [REJECT, DIRECT, 🚀 节点选择] }
  - { name: 🤖 ChatGPT, <<: *pr }
  # 🍎 苹果服务 推荐走全局直连
  - { name: 🍎 苹果服务, <<: *pr }
  - { name: Ⓜ️ 微软云盘, <<: *pr }
  - { name: 🎮 游戏平台, <<: *pr }
  - { name: 📢 谷歌FCM, <<: *pr }
  - { name: 📲 电报服务, <<: *pr }
  - { name: Twitter, <<: *pr }
#  - { name: Pixiv, <<: *pr }
#  - { name: ehentai, <<: *pr }
  # 下面两个看需求启用，打开之后会代理全站流量，可能导致部分版权视频反而无法播放或视频播放速度缓慢
  # 下面 rules 两条也要启用
# - {name: 哔哩哔哩, <<: *pr}
# - {name: 哔哩东南亚, <<: *pr}
#  - { name: 巴哈姆特, <<: *pr }
  - { name: 🎥 油管视频, <<: *pr }
  - { name: 🎥 网飞视频, <<: *pr }
  - { name: Spotify, <<: *pr }
  - { name: 🔍 GitHub, <<: *pr }
  - {
      name: 国内,
      type: select,
      proxies:
        [
          DIRECT,
          🚀 节点选择,
          🇭🇰 香港节点,
          🇨🇳 台湾节点,
          🇯🇵 日本节点,
          🇸🇬 新加坡节点,
          🇺🇲 美国节点,
          其它地区,
          全部节点,
          🔃 自动选择,
        ],
    }
  # 其他就是所有规则没匹配到的
  # 可以理解为 ACL4SSR 配置里的 漏网之鱼
  # 换言之，其他走代理就是绕过中国大陆地址，不走就是 GFWList 模式
  - { name: 其他, <<: *pr }

  # 分隔,下面是地区分组
  - { name: 🇭🇰 香港节点, <<: *use, filter: "(?i)港|hk|hongkong|hong kong" }
  - { name: 🇨🇳 台湾节点, <<: *use, filter: "(?i)台|tw|taiwan" }
  - { name: 🇯🇵 日本节点, <<: *use, filter: "(?i)🇯🇵 日本节点|jp|japan" }
  - { name: 🇺🇲 美国节点, <<: *use, filter: "(?i)美|us|unitedstates|united states" }
  - { name: 🇸🇬 新加坡节点, <<: *use, filter: "(?i)(新|sg|singapore)" }
  - {
      name: 其它地区,
      <<: *use,
      filter: "(?i)^(?!.*(?:🇭🇰|🇯🇵|🇺🇸|🇸🇬|🇨🇳|港|hk|hongkong|台|tw|taiwan|日|jp|japan|新|sg|singapore|美|us|unitedstates)).*",
    }
  - { name: 全部节点, <<: *use }
  - { name: 🔃 自动选择, <<: *use, tolerance: 2, type: url-test }

rules:
  # 若需禁用 QUIC 请取消注释 QUIC 两条规则
  # 防止 🎥 油管视频 等使用 QUIC 导致速度不佳, 禁用 443 端口 UDP 流量（不包括国内）

  - AND,(AND,(DST-PORT,443),(NETWORK,UDP)),(NOT,((GEOSITE,cn))),REJECT # quic
#  - AND,((RULE-SET,anti-AD),(NOT,((RULE-SET,anti-AD-white)))),广告拦截 # 感谢 📲 电报服务 @nextyahooquery 提供的建议
# - GEOSITE,biliintl,哔哩东南亚
# - GEOSITE,bilibili,哔哩哔哩

  # 🤖 ChatGPT (ChatGPT)
  - DOMAIN-SUFFIX,chatgpt.com,🤖 ChatGPT
  - DOMAIN-SUFFIX,oaistatic.com,🤖 ChatGPT
  - DOMAIN-SUFFIX,oaiusercontent.com,🤖 ChatGPT
  - DOMAIN-SUFFIX,openai.com,🤖 ChatGPT
  - DOMAIN-SUFFIX,openai.com.cdn.cloudflare.net,🤖 ChatGPT
  - DOMAIN-SUFFIX,openaiapi-site.azureedge.net,🤖 ChatGPT
  - DOMAIN-SUFFIX,openaicom-api-bdcpf8c6d2e9atf6.z01.azurefd.net,🤖 ChatGPT
  - DOMAIN-SUFFIX,openaicomproductionae4b.blob.core.windows.net,🤖 ChatGPT
  - DOMAIN-SUFFIX,production-openaicom-storage.azureedge.net,🤖 ChatGPT
  # 🤖 ChatGPT 跟踪域名
  - GEOSITE,apple,🍎 苹果服务
  - GEOSITE,onedrive,Ⓜ️ 微软云盘
  - GEOSITE,apple-cn,🍎 苹果服务
#  - GEOSITE,ehentai,ehentai
  - GEOSITE,github,🔍 GitHub
  - GEOSITE,twitter,Twitter
  - GEOSITE,youtube,🎥 油管视频
  - GEOSITE,google,📢 谷歌FCM
  - GEOSITE,google-cn,📢 谷歌FCM # 📢 谷歌FCM CN 不走代理会导致🇭🇰 香港节点等地区节点 Play Store 异常
  - GEOSITE,telegram,📲 电报服务
  - GEOSITE,netflix,🎥 网飞视频
#  - GEOSITE,bahamut,巴哈姆特
#  - GEOSITE,spotify,Spotify
  - GEOSITE,geolocation-!cn,其他
  - AND,(AND,(DST-PORT,443),(NETWORK,UDP)),(NOT,((GEOIP,CN))),REJECT # quic
  - GEOIP,google,📢 谷歌FCM
  - GEOIP,netflix,🎥 网飞视频
  - GEOIP,telegram,📲 电报服务
  - GEOIP,twitter,Twitter
#  - GEOSITE,pixiv,Pixiv
  - GEOSITE,CN,国内
  - GEOIP,CN,国内
  - GEOSITE,steam@cn,DIRECT
  - GEOSITE,steam,🎮 游戏平台
  - MATCH,其他
